version: 0.2

env:
  variables:
    CI: "true"
    REPOSITORY_REGION: "eu-west-2"
    ENV: "prod"
    APP: "weather"
    NAME_CONTAINER: "main"

phases:
  build:
    commands:
      - ls -la
      - docker --version

  post_build:
    commands:
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 873827770697.dkr.ecr.eu-west-2.amazonaws.com
      - cd app
      - docker build -t weather-prod .
      - docker tag weather-prod:latest 873827770697.dkr.ecr.eu-west-2.amazonaws.com/weather-prod:0.2
      - docker push 873827770697.dkr.ecr.eu-west-2.amazonaws.com/weather-prod:0.2