version: 0.2

env:
  variables:
    CI: "true"
    REPOSITORY_REGION: "eu-west-2"
    ENV: "dev"
    APP: "weather"
    NAME_CONTAINER: "main"

phases:
  build:
    commands:
      - ls -la
      - docker --version

  post_build:
    commands:
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 873827770697.dkr.ecr.eu-central-1.amazonaws.com
      - cd app
      - docker build -t terragrunt-dev .
      - docker tag terragrunt-dev:latest 873827770697.dkr.ecr.eu-central-1.amazonaws.com/terragrunt-dev:0.1
      - docker push 873827770697.dkr.ecr.eu-central-1.amazonaws.com/terragrunt-dev:latest